# Generated by Django 6.0 on 2025-12-27 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mastrino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('saldo_dare', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('saldo_avere', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('saldo_finale', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'ordering': ['codice'],
            },
        ),
        migrations.CreateModel(
            name='Esercizio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esercizi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scrittura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descrizione', models.CharField(max_length=255)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conto_avere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimenti_avere', to='core.mastrino')),
                ('conto_dare', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimenti_dare', to='core.mastrino')),
                ('esercizio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scritture', to='core.esercizio')),
            ],
            options={
                'ordering': ['-data', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='esercizio',
            constraint=models.UniqueConstraint(fields=('user', 'nome'), name='unique_esercizio_per_utente'),
        ),
    ]
