# Generated by Django 6.0 on 2026-03-31 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mastrino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Mastrino',
                'verbose_name_plural': 'Mastrini',
                'ordering': ['codice'],
            },
        ),
        migrations.CreateModel(
            name='Esercizio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esercizi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Esercizio',
                'verbose_name_plural': 'Esercizi',
            },
        ),
        migrations.CreateModel(
            name='Operazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descrizione', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('esercizio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operazioni', to='core.esercizio')),
            ],
            options={
                'verbose_name': 'Operazione',
                'verbose_name_plural': 'Operazioni',
                'ordering': ['-data', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RigaOperazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sezione', models.CharField(choices=[('D', 'Dare'), ('A', 'Avere')], max_length=1)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('conto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimenti', to='core.mastrino')),
                ('operazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='core.operazione')),
            ],
            options={
                'verbose_name': 'Riga Operazione',
                'verbose_name_plural': 'Righe Operazioni',
            },
        ),
        migrations.AddConstraint(
            model_name='esercizio',
            constraint=models.UniqueConstraint(fields=('user', 'nome'), name='unique_esercizio_per_utente'),
        ),
    ]
