# Generated by Django 6.0 on 2026-01-02 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esercizio',
            name='data_fine',
        ),
        migrations.RemoveField(
            model_name='esercizio',
            name='data_inizio',
        ),
    ]
