# Generated by Django 6.0 on 2026-03-27 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_esercizio_data_fine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastrino',
            name='saldo_avere',
        ),
        migrations.RemoveField(
            model_name='mastrino',
            name='saldo_dare',
        ),
        migrations.RemoveField(
            model_name='mastrino',
            name='saldo_finale',
        ),
    ]
