# Generated by Django 6.0 on 2026-03-31 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_mastrino_saldo_avere_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='esercizio',
            options={'verbose_name': 'Esercizio', 'verbose_name_plural': 'Esercizi'},
        ),
        migrations.AlterModelOptions(
            name='mastrino',
            options={'ordering': ['codice'], 'verbose_name': 'Mastrino', 'verbose_name_plural': 'Mastrini'},
        ),
        migrations.CreateModel(
            name='Operazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descrizione', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('esercizio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operazioni', to='core.esercizio')),
            ],
            options={
                'verbose_name': 'Operazione',
                'verbose_name_plural': 'Operazioni',
                'ordering': ['-data', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RigaOperazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sezione', models.CharField(choices=[('D', 'Dare'), ('A', 'Avere')], max_length=1)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('conto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimenti', to='core.mastrino')),
                ('operazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='core.operazione')),
            ],
            options={
                'verbose_name': 'Riga Operazione',
                'verbose_name_plural': 'Righe Operazioni',
            },
        ),
        migrations.DeleteModel(
            name='Scrittura',
        ),
    ]
